version: '3.3'

services:
  postgres1:
    image: postgres
    restart: "no"
    container_name: postgres1
    ports:
      - 13101:5432
    environment:
      POSTGRES_PASSWORD: onedb
    volumes:
      - $PWD/config/db1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - owner_net_1

  # sqlite2:
  # sqlite use db2.db file directly

  mysql3:
    image: mysql
    restart: "no"
    container_name: mysql3
    ports:
      - 13103:3306
    environment:
      MYSQL_ROOT_PASSWORD: onedb
      MYSQL_DATABASE: mydb
      TZ: Asia/Shanghai
    volumes:
      - $PWD/config/db3.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - owner_net_3

  # csv4:
  # csv use .csv file directly

networks:
  owner_net_1:
    name: owner_net_1
    driver: bridge
  owner_net_3:
    name: owner_net_3
    driver: bridge
