version: '3.3'

services:
  builder:
    image: maven:3.8-openjdk-11
    container_name: builder
    restart: "no"
    working_dir: /usr/src/build
    command: mvn clean
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD/../..:/usr/src/build