version: '3.3'

services:
  user:
    image: maven:3.8-openjdk-11
    container_name: query_user
    working_dir: /usr/src/mymvn
    restart: "no"
    command: java -jar ./bin/onedb_user_client.jar -m ./config/client.json
    volumes:
      - $PWD/../../../../release/bin:/usr/src/mymvn/bin
      - $PWD/config:/usr/src/mymvn/config
      - $PWD/log:/usr/src/mymvn/log
    networks:
      - public_net

networks:
  public_net:
    external: true
