version: '3.3'

services:
  postgres_3_1:
    image: postgres
    restart: "no"
    container_name: postgres_3_1
    ports:
      - 13101:5432
    environment:
      POSTGRES_PASSWORD: onedb

  postgres_3_2:
    image: postgres
    restart: "no"
    container_name: postgres_3_2
    ports:
      - 13102:5432
    environment:
      POSTGRES_PASSWORD: onedb

  postgres_3_3:
    image: postgres
    restart: "no"
    container_name: postgres_3_3
    ports:
      - 13103:5432
    environment:
      POSTGRES_PASSWORD: onedb