version: '3.3'

services:
  user:
    image: maven:3.8-openjdk-11
    container_name: query_user
    working_dir: /root/onedb
    restart: "no"
    command: java -jar ./bin/onedb_user_client.jar -m ./config/client.json
    volumes:
      - $PWD/../../release/bin:/root/onedb/bin
      - $PWD/config:/root/onedb/config
      - $PWD/log:/root/onedb/log
      - $PWD/cert:/root/onedb/cert
    networks:
      - owner_public_net

networks:
  owner_public_net:
    external: true
