name: Hu-Fu Workflow
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./package.sh

    - name: Upload Hu-Fu Release Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Hu-Fu-release
        path: release
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Hu-Fu Release Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: Hu-Fu-release
        path: release
    - name: Docker Compose Setup
      uses: KengoTODA/actions-setup-docker-compose@v1.0.9
      with:
        version: v2.2.0
    - name: Run Hu-Fu Test
      run: ./test.sh ci
